[package]
name = "varn-lsp"
version.workspace = true
edition.workspace = true

[dependencies]
varn-core    = { path = "../varn-core" }
varn-lexer   = { path = "../varn-lexer" }
varn-parser  = { path = "../varn-parser" }
varn-checker = { path = "../varn-checker" }
varn-modules  = { path = "../varn-modules" }
varn-builtins = { path = "../varn-builtins", features = ["runtime"] }
varn-types    = { path = "../varn-types" }
varn-compiler = { path = "../varn-compiler" }

tower-lsp  = { workspace = true }
tokio      = { workspace = true }
serde_json = { workspace = true }
dashmap    = "5"
once_cell  = "1"
rustc-hash = { workspace = true }


[lints]
workspace = true
