use std::path::{Path, PathBuf};

pub const ENV_DIR_NAME: &str = ".vn";
pub const CACHE_DIR_NAME: &str = "cache";
pub const BYTECODE_DIR_NAME: &str = "bytecode";
pub const TYPES_DIR_NAME: &str = "types";
pub const PACKAGE_MANIFEST_FILE: &str = "varn.toml";
pub const PACKAGE_MANIFEST_FILE_VN: &str = "vn.toml";

// Build fingerprint: hash of the compiler crates' sources, generated by
// build.rs. Any rebuild that could change bytecode/codegen or checker
// serialization semantics yields a new value, so stale `.vnc`/`.vnm`/`.vnb`
// artifacts invalidate automatically — no manual version bumps. Toolchain
// changes (rustc, dep versions) are not captured; sources dominate drift.
include!(concat!(env!("OUT_DIR"), "/build_fingerprint.rs"));

pub const MAGIC_WRC: &[u8; 4] = b"WRC\0";
pub const MAGIC_VNC: &[u8; 4] = b"VNC\0";
pub const MAGIC_VNM: &[u8; 4] = b"VNM\0";
pub const MAGIC_VNB: &[u8; 4] = b"VNB\0";
pub const MAGIC_VEXE: &[u8; 4] = b"VEXE";
pub const VNB_FORMAT_VERSION: u32 = 2;

pub fn find_project_root(start_path: &Path) -> PathBuf {
    start_path
        .ancestors()
        .find(|dir| {
            dir.join(PACKAGE_MANIFEST_FILE).exists()
                || dir.join(PACKAGE_MANIFEST_FILE_VN).exists()
        })
        .unwrap_or(start_path)
        .to_path_buf()
}

pub fn global_varn_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("VARN_HOME") {
        return PathBuf::from(dir);
    }
    if let Some(home) = dirs_home() {
        return home.join(".varn");
    }
    PathBuf::from(".varn")
}

pub fn get_cache_dir(_project_root: &Path) -> PathBuf {
    if let Ok(dir) = std::env::var("VARN_CACHE_DIR") {
        return PathBuf::from(dir);
    }
    global_varn_dir().join(CACHE_DIR_NAME)
}

pub fn get_bytecode_cache_dir(project_root: &Path) -> PathBuf {
    get_cache_dir(project_root).join(BYTECODE_DIR_NAME)
}

pub fn get_types_cache_dir(project_root: &Path) -> PathBuf {
    get_cache_dir(project_root).join(TYPES_DIR_NAME)
}

fn dirs_home() -> Option<PathBuf> {
    #[cfg(windows)]
    {
        std::env::var_os("USERPROFILE")
            .or_else(|| std::env::var_os("HOME"))
            .map(PathBuf::from)
    }
    #[cfg(not(windows))]
    {
        std::env::var_os("HOME").map(PathBuf::from)
    }
}

pub fn write_envelope(magic: &[u8; 4], version: u32, payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(8 + payload.len());
    out.extend_from_slice(magic);
    out.extend_from_slice(&version.to_le_bytes());
    out.extend_from_slice(payload);
    out
}

pub fn read_envelope<'a>(
    magic: &[u8; 4],
    expected_version: u32,
    bytes: &'a [u8],
) -> Result<&'a [u8], &'static str> {
    if bytes.len() < 8 {
        return Err("invalid artifact: file too short");
    }
    if &bytes[..4] != magic {
        return Err("invalid artifact: bad magic header");
    }
    let version = u32::from_le_bytes(bytes[4..8].try_into().unwrap());
    if version != expected_version {
        return Err("invalid artifact: version mismatch");
    }
    Ok(&bytes[8..])
}
