use std::path::{Path, PathBuf};

pub const ENV_DIR_NAME: &str = ".vn";
pub const CACHE_DIR_NAME: &str = "cache";
pub const BYTECODE_DIR_NAME: &str = "bytecode";
pub const TYPES_DIR_NAME: &str = "types";
pub const PACKAGE_MANIFEST_FILE: &str = "varn.toml";
pub const PACKAGE_MANIFEST_FILE_VN: &str = "vn.toml";

// Schema fingerprint: hash of `varn-types` and `varn-modules` sources,
// generated by build.rs. It describes the SHAPE of the serialized artifact,
// so a `.vnc`/`.vnm`/`.vnb` written under a different value cannot be
// deserialized and must be rejected.
//
// It deliberately does NOT cover the crates that PRODUCE bytecode
// (`varn-compiler`, `varn-checker`, the frontend): watching those from a
// build script that every one of them depends on would recompile the whole
// graph on each edit. Producer identity is [`producer_fingerprint`] instead,
// resolved at runtime — see [`artifact_key`], which is what artifacts are
// actually keyed by.
include!(concat!(env!("OUT_DIR"), "/build_fingerprint.rs"));

/// Identity of the binary that produced an artifact: path, size and mtime of
/// the running executable, folded to `u32`.
///
/// Cached artifacts are the OUTPUT of the compiler, so the compiler is part
/// of their key. [`BUILD_FINGERPRINT`] cannot supply that — it watches only
/// the two schema crates, so a `varn-compiler` change left `.vnc` files
/// looking valid and an updated `vn` ran bytecode its predecessor emitted
/// until someone ran `vn cache clean`. That was a correctness bug, not a
/// stale-performance one: the cached bytecode predates every compiler fix.
///
/// Reading the executable's metadata rather than hashing its ~13 MB keeps
/// this to one `stat`; a full content hash would cost more than the ~10 ms
/// startup it is meant to protect. Two builds differ in mtime, and usually in
/// size too. The path is folded in as well, so two binaries compared
/// side by side (`compare.ps1 -Baseline`) never share an artifact file even
/// when both were built from the same sources.
///
/// Copying the binary changes its mtime and costs one recompilation. That is
/// the right direction to err: a missed invalidation runs stale code, a
/// spurious one only recompiles.
pub fn producer_fingerprint() -> u32 {
    static FP: std::sync::OnceLock<u32> = std::sync::OnceLock::new();
    *FP.get_or_init(|| {
        let mut hash: u64 = 0xcbf29ce484222325;
        let mut eat = |bytes: &[u8]| {
            for b in bytes {
                hash ^= *b as u64;
                hash = hash.wrapping_mul(0x100000001b3);
            }
        };
        match std::env::current_exe() {
            Ok(exe) => {
                eat(exe.to_string_lossy().as_bytes());
                if let Ok(meta) = std::fs::metadata(&exe) {
                    eat(&meta.len().to_le_bytes());
                    if let Ok(modified) = meta.modified() {
                        if let Ok(since) = modified.duration_since(std::time::UNIX_EPOCH) {
                            eat(&since.as_nanos().to_le_bytes());
                        }
                    }
                }
            }
            // No executable identity available: fall back to a constant, which
            // degrades to the old behaviour rather than to a random key that
            // would make the cache useless.
            Err(_) => eat(b"varn-unknown-producer"),
        }
        (hash ^ (hash >> 32)) as u32
    })
}

/// Clave con la que se NOMBRA una entrada de caché en disco: esquema e
/// identidad del productor juntos.
///
/// Va en el nombre del archivo además de en la envolvente, y por un motivo
/// distinto: la envolvente decide si una entrada es *válida*, el nombre decide
/// de *quién* es. Sin ella dos binarios comparten ruta, se sobreescriben la
/// entrada en cada ejecución y ninguno reutiliza nada — el artefacto seguiría
/// siendo correcto, pero la caché dejaría de servir para lo que existe.
///
/// La validez la aplica [`read_artifact`] a partir de [`ArtifactClass`].
pub fn cache_key() -> u32 {
    BUILD_FINGERPRINT ^ producer_fingerprint()
}

/// Poda las entradas del MISMO artefacto lógico selladas por otra clave,
/// conservando las [`ARTIFACT_GENERATIONS`] más recientes (la recién escrita
/// incluida).
///
/// Poner [`artifact_key`] en el nombre del archivo es lo que impide que dos
/// binarios se pisen la caché, pero sin poda cada rebuild dejaría su entrada
/// atrás y el directorio global crecería sin límite.
///
/// Conservar varias, y no sólo la última, es lo que hace utilizable comparar
/// dos binarios alternándolos (`compare.ps1 -Baseline`): con una sola
/// generación cada corrida expulsa la del otro y ambos recompilan siempre,
/// que es precisamente el ruido que este cambio existe para eliminar.
///
/// Se llama DESPUÉS de escribir, para que el archivo nuevo cuente como la
/// generación más reciente. `current` se espera con la forma
/// `<prefijo>.<clave>.<ext>`; los hermanos comparten `<prefijo>` y `<ext>`.
pub fn prune_superseded(current: &Path) {
    let (Some(dir), Some(name), Some(ext)) = (
        current.parent(),
        current.file_name().and_then(|n| n.to_str()),
        current.extension().and_then(|e| e.to_str()),
    ) else {
        return;
    };
    // Recorta `<clave>.<ext>` para quedarse con el prefijo, que identifica al
    // archivo fuente. Un stem con puntos propios no molesta: se cuenta desde
    // el final.
    let suffix = format!(".{ext}");
    let Some(without_ext) = name.strip_suffix(&suffix) else {
        return;
    };
    let Some(dot) = without_ext.rfind('.') else {
        return;
    };
    let prefix = without_ext[..=dot].to_owned();

    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    let mut siblings: Vec<(std::time::SystemTime, PathBuf)> = entries
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            let other = path.file_name()?.to_str()?;
            if !other.starts_with(&prefix) || !other.ends_with(&suffix) {
                return None;
            }
            let modified = entry.metadata().ok()?.modified().ok()?;
            Some((modified, path))
        })
        .collect();
    if siblings.len() <= ARTIFACT_GENERATIONS {
        return;
    }
    siblings.sort_by(|a, b| b.0.cmp(&a.0));
    for (_, path) in siblings.drain(ARTIFACT_GENERATIONS..) {
        let _ = std::fs::remove_file(path);
    }
}

/// Cuántas claves distintas se conservan por artefacto lógico. Tres deja sitio
/// a comparar dos binarios y a un tercero recién compilado sin que ninguno
/// pierda su entrada, y acota el directorio a un múltiplo pequeño.
pub const ARTIFACT_GENERATIONS: usize = 3;

/// Cabecera única de todo artefacto serializado de Varn.
///
/// Antes había cuatro magics (`WRC`, `VNC`, `VNM`, `VNB`) para dos payloads
/// reales: el grafo de módulos compilado y la interfaz del checker. `WRC` y
/// `VNC` envolvían el MISMO tipo, y su única diferencia era la política de
/// versión — que elegía el sitio de llamada, no el artefacto. Nada dentro de
/// un archivo decía de qué clase era, así que sellar un distribuible con la
/// clave de una caché compilaba, pasaba los tests, y sólo se notaba al llevar
/// el `.vnc` a otra máquina. Ahora la clase viaja DENTRO y la validación se
/// deriva de ella.
pub const MAGIC: &[u8; 4] = b"VARN";

/// Marcador de cola de un ejecutable standalone. No es una envolvente: son los
/// últimos cuatro bytes del `.exe`, que señalan que lleva un artefacto pegado.
pub const MAGIC_VEXE: &[u8; 4] = b"VEXE";

/// Versión de esta CABECERA. Sube sólo si cambia la disposición de los campos,
/// no cuando cambia el contenido del payload — de eso responde
/// [`BUILD_FINGERPRINT`].
const ENVELOPE_VERSION: u16 = 1;

/// Qué lleva el payload. Lo comprueba el lector, que sabe qué esperaba: pedir
/// un grafo y encontrar una interfaz del checker es un error de programa, y se
/// diagnostica como tal en vez de como "magic incorrecto".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum ArtifactKind {
    /// `ModuleGraphArtifact`: grafo de módulos compilado a bytecode.
    ModuleGraph = 1,
    /// `CachedModule` de varn-checker: interfaz (exports + binds) de un módulo.
    CheckerInterface = 2,
    /// `StdBundle`: interfaces, bytecode y fuentes de toda la stdlib.
    StdBundle = 3,
}

impl ArtifactKind {
    fn from_u16(v: u16) -> Option<Self> {
        match v {
            1 => Some(Self::ModuleGraph),
            2 => Some(Self::CheckerInterface),
            3 => Some(Self::StdBundle),
            _ => None,
        }
    }

    fn name(self) -> &'static str {
        match self {
            Self::ModuleGraph => "grafo de modulos",
            Self::CheckerInterface => "interfaz de checker",
            Self::StdBundle => "bundle de stdlib",
        }
    }
}

/// Para qué existe el artefacto, que es lo que determina cómo se valida.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum ArtifactClass {
    /// Detalle de implementación regenerable bajo `~/.varn/cache`. Se sella
    /// también con la identidad del productor: es la salida de ESTE compilador
    /// y no debe sobrevivirle. Si no casa, se recompila en silencio.
    Cache = 1,
    /// Producto que el usuario mueve: `vn build`, ejecutables standalone, el
    /// bundle de std. Viaja a otra máquina y lo ejecuta otro binario, así que
    /// sólo puede depender del esquema. Si no casa, es un error que se reporta
    /// a quien lo ejecuta.
    Distributable = 2,
}

impl ArtifactClass {
    fn from_u8(v: u8) -> Option<Self> {
        match v {
            1 => Some(Self::Cache),
            2 => Some(Self::Distributable),
            _ => None,
        }
    }

    /// La identidad de productor que corresponde sellar para esta clase.
    fn producer_stamp(self) -> u32 {
        match self {
            Self::Cache => producer_fingerprint(),
            Self::Distributable => 0,
        }
    }
}

/// Por qué se rechazó un artefacto. La distinción importa: [`Self::Superseded`]
/// es la operación normal de una caché y se recompila sin decir nada, mientras
/// que los demás son archivos que no deberían estar ahí.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ArtifactError {
    TooShort,
    BadMagic,
    /// Cabecera de una versión de Varn que este binario no entiende.
    UnknownEnvelope(u16),
    UnknownKind(u16),
    UnknownClass(u8),
    /// Se pidió un tipo y el archivo lleva otro.
    WrongKind {
        expected: ArtifactKind,
        found: ArtifactKind,
    },
    /// Emitido por otro build: esquema o productor distintos.
    Superseded,
    /// El payload no coincide con su checksum: escritura a medias, disco con
    /// bit podrido o edición del archivo.
    Corrupt,
}

impl std::fmt::Display for ArtifactError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TooShort => write!(f, "artefacto truncado"),
            Self::BadMagic => write!(f, "no es un artefacto de Varn"),
            Self::UnknownEnvelope(v) => {
                write!(f, "cabecera de artefacto v{v}, no reconocida por este vn")
            }
            Self::UnknownKind(k) => write!(f, "tipo de artefacto desconocido ({k})"),
            Self::UnknownClass(c) => write!(f, "clase de artefacto desconocida ({c})"),
            Self::WrongKind { expected, found } => write!(
                f,
                "se esperaba {}, el archivo lleva {}",
                expected.name(),
                found.name()
            ),
            Self::Superseded => write!(f, "compilado por otra version de Varn"),
            Self::Corrupt => write!(f, "artefacto corrupto (checksum no coincide)"),
        }
    }
}

/// FNV-1a de 32 bits sobre el payload. No es criptográfico y no pretende
/// serlo: detecta escrituras a medias y corrupción de disco, no manipulación
/// deliberada — quien puede reescribir el archivo puede recalcular el
/// checksum, y de todas formas ejecutar un artefacto ya es ejecutar código.
fn payload_checksum(payload: &[u8]) -> u32 {
    let mut hash: u32 = 0x811c9dc5;
    for &b in payload {
        hash ^= b as u32;
        hash = hash.wrapping_mul(0x0100_0193);
    }
    hash
}

pub fn find_project_root(start_path: &Path) -> PathBuf {
    start_path
        .ancestors()
        .find(|dir| {
            dir.join(PACKAGE_MANIFEST_FILE).exists()
                || dir.join(PACKAGE_MANIFEST_FILE_VN).exists()
        })
        .unwrap_or(start_path)
        .to_path_buf()
}

pub fn global_varn_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("VARN_HOME") {
        return PathBuf::from(dir);
    }
    if let Some(home) = dirs_home() {
        return home.join(".varn");
    }
    PathBuf::from(".varn")
}

pub fn get_cache_dir(_project_root: &Path) -> PathBuf {
    if let Ok(dir) = std::env::var("VARN_CACHE_DIR") {
        return PathBuf::from(dir);
    }
    global_varn_dir().join(CACHE_DIR_NAME)
}

pub fn get_bytecode_cache_dir(project_root: &Path) -> PathBuf {
    get_cache_dir(project_root).join(BYTECODE_DIR_NAME)
}

pub fn get_types_cache_dir(project_root: &Path) -> PathBuf {
    get_cache_dir(project_root).join(TYPES_DIR_NAME)
}

fn dirs_home() -> Option<PathBuf> {
    #[cfg(windows)]
    {
        std::env::var_os("USERPROFILE")
            .or_else(|| std::env::var_os("HOME"))
            .map(PathBuf::from)
    }
    #[cfg(not(windows))]
    {
        std::env::var_os("HOME").map(PathBuf::from)
    }
}

/// Disposición de la cabecera, 21 bytes:
///
/// ```text
/// [0..4)   magic "VARN"
/// [4..6)   ENVELOPE_VERSION  u16 LE
/// [6..8)   ArtifactKind      u16 LE
/// [8..9)   ArtifactClass     u8
/// [9..13)  BUILD_FINGERPRINT u32 LE   forma del payload
/// [13..17) productor         u32 LE   0 en los distribuibles
/// [17..21) checksum          u32 LE   FNV-1a del payload
/// [21..)   payload
/// ```
const HEADER_LEN: usize = 21;

/// Sella un payload. La `class` decide sola qué identidad de productor se
/// graba, así que quien escribe no puede equivocarse de política: declara para
/// qué es el artefacto y el resto se deriva.
pub fn write_artifact(kind: ArtifactKind, class: ArtifactClass, payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(HEADER_LEN + payload.len());
    out.extend_from_slice(MAGIC);
    out.extend_from_slice(&ENVELOPE_VERSION.to_le_bytes());
    out.extend_from_slice(&(kind as u16).to_le_bytes());
    out.push(class as u8);
    out.extend_from_slice(&BUILD_FINGERPRINT.to_le_bytes());
    out.extend_from_slice(&class.producer_stamp().to_le_bytes());
    out.extend_from_slice(&payload_checksum(payload).to_le_bytes());
    out.extend_from_slice(payload);
    out
}

/// Valida y devuelve el payload. `expected` es lo que el llamante va a
/// deserializar; que no coincida es un error de programa, no un artefacto
/// obsoleto, y se distingue como tal.
///
/// La regla de caducidad NO la pone el llamante: sale de la `class` grabada en
/// el archivo. Un distribuible se acepta en cualquier máquina mientras el
/// esquema case; una entrada de caché exige además haber salido de este mismo
/// binario.
pub fn read_artifact(expected: ArtifactKind, bytes: &[u8]) -> Result<&[u8], ArtifactError> {
    if bytes.len() < HEADER_LEN {
        return Err(ArtifactError::TooShort);
    }
    if &bytes[..4] != MAGIC {
        return Err(ArtifactError::BadMagic);
    }
    let envelope = u16::from_le_bytes(bytes[4..6].try_into().unwrap());
    if envelope != ENVELOPE_VERSION {
        return Err(ArtifactError::UnknownEnvelope(envelope));
    }
    let raw_kind = u16::from_le_bytes(bytes[6..8].try_into().unwrap());
    let Some(kind) = ArtifactKind::from_u16(raw_kind) else {
        return Err(ArtifactError::UnknownKind(raw_kind));
    };
    if kind != expected {
        return Err(ArtifactError::WrongKind {
            expected,
            found: kind,
        });
    }
    let Some(class) = ArtifactClass::from_u8(bytes[8]) else {
        return Err(ArtifactError::UnknownClass(bytes[8]));
    };
    let schema = u32::from_le_bytes(bytes[9..13].try_into().unwrap());
    if schema != BUILD_FINGERPRINT {
        return Err(ArtifactError::Superseded);
    }
    let producer = u32::from_le_bytes(bytes[13..17].try_into().unwrap());
    if producer != class.producer_stamp() {
        return Err(ArtifactError::Superseded);
    }
    let expected_sum = u32::from_le_bytes(bytes[17..21].try_into().unwrap());
    let payload = &bytes[HEADER_LEN..];
    // postcard no lleva descripción del esquema, así que detecta la corrupción
    // sólo cuando produce una longitud imposible. Alterar bytes DENTRO de un
    // `Vec<u16>` de bytecode deserializa perfectamente y se ejecutaría sin que
    // nada lo notara; el checksum es lo que convierte eso en un error.
    if payload_checksum(payload) != expected_sum {
        return Err(ArtifactError::Corrupt);
    }
    Ok(payload)
}

/// Escribe un artefacto de forma que ningún lector pueda ver una versión a
/// medias: a un temporal en el mismo directorio y luego `rename`, que es
/// atómico dentro de un volumen.
///
/// `fs::write` trunca y va llenando, así que un `vn` concurrente —el LSP y una
/// terminal a la vez es lo normal— o un Ctrl-C dejan una entrada parcial en su
/// sitio definitivo. Con checksum eso se detecta, pero se detecta *después* de
/// haber perdido la entrada; con rename no llega a ocurrir.
pub fn write_artifact_file(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    let tmp = path.with_extension(format!("tmp{}", std::process::id()));
    std::fs::write(&tmp, bytes)?;
    match std::fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(e) => {
            let _ = std::fs::remove_file(&tmp);
            Err(e)
        }
    }
}
