[package]
name = "varn-types"
version = "0.1.0"
edition = "2021"

[dependencies]
varn-core    = { path = "../varn-core" }
varn-base    = { path = "../varn-base" }
parking_lot  = { workspace = true }
rust_decimal = { workspace = true }
rustc-hash   = { workspace = true }
serde        = { workspace = true, features = ["rc"] }
