[package]
name = "varn-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
varn-core        = { path = "../varn-core" }
varn-diagnostics = { path = "../varn-diagnostics" }
varn-types       = { path = "../varn-types" }
rustc-hash       = { workspace = true }
rust_decimal     = { workspace = true }
