[package]
name = "varn-vm"
version = "0.1.0"
edition = "2021"

[features]
profiling = []

[dependencies]
varn-types    = { path = "../varn-types" }
varn-core     = { path = "../varn-core" }
varn-builtins = { path = "../varn-builtins", features = ["runtime"] }
varn-runtime  = { path = "../varn-runtime" }
tokio         = { version = "1", features = ["time", "rt"] }
varn-modules  = { path = "../varn-modules" }
varn-base     = { path = "../varn-base" }
parking_lot   = { workspace = true }
rust_decimal  = { workspace = true }
rustc-hash    = { workspace = true }
varn-jit      = { path = "../varn-jit" }

