[package]
name = "varn-vm"
version.workspace = true
edition.workspace = true

[features]
profiling = []

[dependencies]
varn-types    = { path = "../varn-types" }
varn-core     = { path = "../varn-core" }
varn-builtins = { path = "../varn-builtins", features = ["runtime"] }
varn-runtime  = { path = "../varn-runtime" }
varn-modules  = { path = "../varn-modules" }
rust_decimal  = { workspace = true }
rustc-hash    = { workspace = true }
varn-jit      = { path = "../varn-jit" }
serde         = { workspace = true }
serde_json    = { workspace = true }
ryu           = { workspace = true }
memchr        = { workspace = true }


[lints]
workspace = true
