#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum ErrorCode {
    UnterminatedString = 1001,
    InvalidNumericLiteral = 1002,
    UnknownCharacter = 1003,
    UnterminatedTemplate = 1004,
    UnterminatedRegex = 1005,
    InvalidEscapeSequence = 1006,
    UnterminatedBlockComment = 1007,
    InvalidUnicodeEscape = 1008,

    ExpectedToken = 2001,
    UnexpectedToken = 2002,
    UnterminatedParen = 2003,
    UnterminatedBrace = 2004,
    UnterminatedBracket = 2005,
    InvalidExpression = 2006,
    InvalidStatement = 2007,
    InvalidTypeAnnotation = 2008,
    InvalidPattern = 2009,
    InvalidImportPath = 2010,
    DuplicateLabel = 2011,
    InvalidPropertyName = 2012,
    InvalidDecoratorTarget = 2013,
    ArrowWithoutParens = 2014,
    InvalidGeneratorYield = 2015,
    CircularModuleDependency = 2016,
    ExportNotFound = 2017,
    InvalidRestElement = 2018,
    MultipleRestElements = 2019,
    ConstWithoutInitializer = 2020,

    TypeMismatch = 3001,
    UnknownSymbol = 3002,
    NotCallable = 3003,
    MissingProperty = 3004,
    NotAssignable = 3005,
    NotIndexable = 3006,
    InvalidUnionMember = 3007,
    InvalidIntersection = 3008,
    CircularTypeReference = 3009,
    InvalidTypeOperator = 3010,
    TypeAnnotationRequired = 3011,
    InvalidTypeofTarget = 3012,
    InvalidInstanceofTarget = 3013,
    InvalidAsCast = 3014,
    InvalidSatisfies = 3015,
    TupleIndexOutOfBounds = 3016,
    TupleArityMismatch = 3017,
    RecordShapeMismatch = 3018,
    InvalidConstAssertion = 3019,
    InfiniteTypeExpansion = 3020,

    TypeArgInferenceFailed = 3201,
    ConstraintViolation = 3202,
    WrongTypeArgCount = 3203,
    InvalidTypeParamConstraint = 3204,
    GenericNotApplicableHere = 3205,

    PossibleNullDereference = 3301,
    NullNotAllowed = 3302,
    OptionalChainOnNonNullable = 3303,

    NonExhaustiveMatch = 4001,
    DuplicateDeclaration = 4002,
    UseBeforeDeclaration = 4003,
    UnreachableCode = 4004,
    InvalidBreakTarget = 4005,
    InvalidContinueTarget = 4006,
    ReturnOutsideFunction = 4007,
    InvalidThrowOperand = 4008,
    DuplicateCaseLabel = 4009,
    InvalidPipelineReceiver = 4010,
    AwaitOutsideAsync = 4011,
    YieldOutsideGenerator = 4012,
    RedundantMatchArm = 4013,
    InvalidDestructuringTarget = 4014,
    MatchPatternTypeMismatch = 4015,
    InvalidUsingTarget = 4016,

    MissingOverride = 4101,
    SpuriousOverride = 4102,
    NotASubclass = 4103,
    PrivateMemberAccess = 4104,
    ProtectedMemberAccess = 4105,
    StaticMemberOnInstance = 4106,
    AbstractMethodNotImplemented = 4107,
    ConstructorNotCalled = 4108,
    InvalidSuperCall = 4109,
    DuplicateMemberName = 4110,
    InvalidExtensionTarget = 4111,
    AmbiguousExtensionMethod = 4112,
    InvalidExtensionReceiver = 4113,
    SuperOutsideMethod = 4114,

    InvalidIsolateTransfer = 4201,
    ChannelClosedError = 4202,
    InvalidTaskSpawn = 4203,
    InvalidChannelCapacity = 4204,
    IsolateExecutionTimeout = 4205,
    InvalidMutexAccess = 4206,

    PermissionDenied = 4301,
    CapabilityViolation = 4302,
    InvalidHostHandle = 4303,
    RestrictedApiAccess = 4304,

    InvalidDecoratorSignature = 4401,
    MetadataNotFound = 4402,
    InvalidReflectionTarget = 4403,
    ReflectionSecurityViolation = 4404,

    UnsupportedExpression = 5001,
    UnsupportedStatement = 5002,
    UnsupportedPattern = 5003,
    UnsupportedTypeNode = 5004,
    CompilationInternalError = 5005,
    BytecodeOverflow = 5006,
    ConstantPoolOverflow = 5007,
}

impl ErrorCode {
    pub fn name(self) -> &'static str {
        match self {
            ErrorCode::UnterminatedString => "unterminated-string",
            ErrorCode::InvalidNumericLiteral => "invalid-numeric-literal",
            ErrorCode::UnknownCharacter => "unknown-character",
            ErrorCode::UnterminatedTemplate => "unterminated-template",
            ErrorCode::UnterminatedRegex => "unterminated-regex",
            ErrorCode::InvalidEscapeSequence => "invalid-escape-sequence",
            ErrorCode::UnterminatedBlockComment => "unterminated-block-comment",
            ErrorCode::InvalidUnicodeEscape => "invalid-unicode-escape",

            ErrorCode::ExpectedToken => "expected-token",
            ErrorCode::UnexpectedToken => "unexpected-token",
            ErrorCode::UnterminatedParen => "unterminated-paren",
            ErrorCode::UnterminatedBrace => "unterminated-brace",
            ErrorCode::UnterminatedBracket => "unterminated-bracket",
            ErrorCode::InvalidExpression => "invalid-expression",
            ErrorCode::InvalidStatement => "invalid-statement",
            ErrorCode::InvalidTypeAnnotation => "invalid-type-annotation",
            ErrorCode::InvalidPattern => "invalid-pattern",
            ErrorCode::InvalidImportPath => "invalid-import-path",
            ErrorCode::DuplicateLabel => "duplicate-label",
            ErrorCode::InvalidPropertyName => "invalid-property-name",
            ErrorCode::InvalidDecoratorTarget => "invalid-decorator-target",
            ErrorCode::ArrowWithoutParens => "arrow-without-parens",
            ErrorCode::InvalidGeneratorYield => "invalid-generator-yield",
            ErrorCode::CircularModuleDependency => "circular-module-dependency",
            ErrorCode::ExportNotFound => "export-not-found",
            ErrorCode::InvalidRestElement => "invalid-rest-element",
            ErrorCode::MultipleRestElements => "multiple-rest-elements",
            ErrorCode::ConstWithoutInitializer => "const-without-initializer",

            ErrorCode::TypeMismatch => "type-mismatch",
            ErrorCode::UnknownSymbol => "unknown-symbol",
            ErrorCode::NotCallable => "not-callable",
            ErrorCode::MissingProperty => "missing-property",
            ErrorCode::NotAssignable => "not-assignable",
            ErrorCode::NotIndexable => "not-indexable",
            ErrorCode::InvalidUnionMember => "invalid-union-member",
            ErrorCode::InvalidIntersection => "invalid-intersection",
            ErrorCode::CircularTypeReference => "circular-type-reference",
            ErrorCode::InvalidTypeOperator => "invalid-type-operator",
            ErrorCode::TypeAnnotationRequired => "type-annotation-required",
            ErrorCode::InvalidTypeofTarget => "invalid-typeof-target",
            ErrorCode::InvalidInstanceofTarget => "invalid-instanceof-target",
            ErrorCode::InvalidAsCast => "invalid-as-cast",
            ErrorCode::InvalidSatisfies => "invalid-satisfies",
            ErrorCode::TupleIndexOutOfBounds => "tuple-index-out-of-bounds",
            ErrorCode::TupleArityMismatch => "tuple-arity-mismatch",
            ErrorCode::RecordShapeMismatch => "record-shape-mismatch",
            ErrorCode::InvalidConstAssertion => "invalid-const-assertion",
            ErrorCode::InfiniteTypeExpansion => "infinite-type-expansion",

            ErrorCode::TypeArgInferenceFailed => "type-arg-inference-failed",
            ErrorCode::ConstraintViolation => "constraint-violation",
            ErrorCode::WrongTypeArgCount => "wrong-type-arg-count",
            ErrorCode::InvalidTypeParamConstraint => "invalid-type-param-constraint",
            ErrorCode::GenericNotApplicableHere => "generic-not-applicable-here",

            ErrorCode::PossibleNullDereference => "possible-null-dereference",
            ErrorCode::NullNotAllowed => "null-not-allowed",
            ErrorCode::OptionalChainOnNonNullable => "optional-chain-on-non-nullable",

            ErrorCode::NonExhaustiveMatch => "non-exhaustive-match",
            ErrorCode::DuplicateDeclaration => "duplicate-declaration",
            ErrorCode::UseBeforeDeclaration => "use-before-declaration",
            ErrorCode::UnreachableCode => "unreachable-code",
            ErrorCode::InvalidBreakTarget => "invalid-break-target",
            ErrorCode::InvalidContinueTarget => "invalid-continue-target",
            ErrorCode::ReturnOutsideFunction => "return-outside-function",
            ErrorCode::InvalidThrowOperand => "invalid-throw-operand",
            ErrorCode::DuplicateCaseLabel => "duplicate-case-label",
            ErrorCode::InvalidPipelineReceiver => "invalid-pipeline-receiver",
            ErrorCode::AwaitOutsideAsync => "await-outside-async",
            ErrorCode::YieldOutsideGenerator => "yield-outside-generator",
            ErrorCode::RedundantMatchArm => "redundant-match-arm",
            ErrorCode::InvalidDestructuringTarget => "invalid-destructuring-target",
            ErrorCode::MatchPatternTypeMismatch => "match-pattern-type-mismatch",
            ErrorCode::InvalidUsingTarget => "invalid-using-target",

            ErrorCode::MissingOverride => "missing-override",
            ErrorCode::SpuriousOverride => "spurious-override",
            ErrorCode::NotASubclass => "not-a-subclass",
            ErrorCode::PrivateMemberAccess => "private-member-access",
            ErrorCode::ProtectedMemberAccess => "protected-member-access",
            ErrorCode::StaticMemberOnInstance => "static-member-on-instance",
            ErrorCode::AbstractMethodNotImplemented => "abstract-method-not-implemented",
            ErrorCode::ConstructorNotCalled => "constructor-not-called",
            ErrorCode::InvalidSuperCall => "invalid-super-call",
            ErrorCode::DuplicateMemberName => "duplicate-member-name",
            ErrorCode::InvalidExtensionTarget => "invalid-extension-target",
            ErrorCode::AmbiguousExtensionMethod => "ambiguous-extension-method",
            ErrorCode::InvalidExtensionReceiver => "invalid-extension-receiver",
            ErrorCode::SuperOutsideMethod => "super-outside-method",

            ErrorCode::InvalidIsolateTransfer => "invalid-isolate-transfer",
            ErrorCode::ChannelClosedError => "channel-closed-error",
            ErrorCode::InvalidTaskSpawn => "invalid-task-spawn",
            ErrorCode::InvalidChannelCapacity => "invalid-channel-capacity",
            ErrorCode::IsolateExecutionTimeout => "isolate-execution-timeout",
            ErrorCode::InvalidMutexAccess => "invalid-mutex-access",

            ErrorCode::PermissionDenied => "permission-denied",
            ErrorCode::CapabilityViolation => "capability-violation",
            ErrorCode::InvalidHostHandle => "invalid-host-handle",
            ErrorCode::RestrictedApiAccess => "restricted-api-access",

            ErrorCode::InvalidDecoratorSignature => "invalid-decorator-signature",
            ErrorCode::MetadataNotFound => "metadata-not-found",
            ErrorCode::InvalidReflectionTarget => "invalid-reflection-target",
            ErrorCode::ReflectionSecurityViolation => "reflection-security-violation",

            ErrorCode::UnsupportedExpression => "unsupported-expression",
            ErrorCode::UnsupportedStatement => "unsupported-statement",
            ErrorCode::UnsupportedPattern => "unsupported-pattern",
            ErrorCode::UnsupportedTypeNode => "unsupported-type-node",
            ErrorCode::CompilationInternalError => "compilation-internal-error",
            ErrorCode::BytecodeOverflow => "bytecode-overflow",
            ErrorCode::ConstantPoolOverflow => "constant-pool-overflow",
        }
    }

    pub fn category(self) -> &'static str {
        match self as u32 {
            1000..=1999 => "Lexer",
            2000..=2999 => "Parser",
            3000..=3999 => "TypeChecker",
            4000..=4999 => "Semantic",
            5000..=5999 => "Compiler",
            _ => "General",
        }
    }

    pub fn code_number(self) -> u32 {
        self as u32
    }
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "VN{}", *self as u32)
    }
}
