pub mod arch;
pub(crate) mod clif_link;
pub(crate) mod closure;
pub(crate) mod error;
pub mod exec;
pub(crate) mod frame;
pub(crate) mod frame_stack;
pub(crate) mod gc;
pub(crate) mod generator;
pub mod globals;
pub(crate) mod heap;
pub(crate) mod heap_array;
mod heap_str_alloc;
pub mod jit;
mod jit_layout;
pub(crate) mod linker;
pub mod loader;
pub(crate) mod nursery;
pub(crate) mod profile;
pub(crate) mod settings;
pub(crate) mod strbuf;
pub(crate) mod value;
pub(crate) mod vm;

pub use error::{FrameInfo, RuntimeError, VmResult};
pub use globals::GlobalStore;
pub use heap::{Heap, HeapObj};
pub use loader::{CompositeLoader, ModuleError, ModuleLoader};
pub use profile::{CallEntry, HotspotCounters, ProfileCounters, VmProfile};
pub use settings::ExecSettings;
pub use value::VmValue;
pub use varn_jit;
pub use vm::{prefill_native_modules, Vm};
