pub mod alloc_profile;
pub mod arch;
pub(crate) mod clif_link;
pub(crate) mod closure;
pub mod debug;
pub(crate) mod error;
pub mod exec;
pub(crate) mod frame;
pub(crate) mod frame_stack;
pub(crate) mod frame_store;
pub(crate) mod frame_store_abi;
pub(crate) mod frame_store_convert;
pub(crate) mod frame_store_query;
pub(crate) mod frame_store_regs;
pub(crate) mod frame_store_roots;
pub mod gc_report;
pub mod gc_trace;
pub(crate) mod generator;
pub mod globals;
pub(crate) mod heap;
pub(crate) mod heap_array;
mod heap_str_alloc;
pub(crate) mod home_trace;
pub mod jit;
pub(crate) mod linker;
pub mod loader;
pub(crate) mod profile;
pub(crate) mod settings;
pub(crate) mod strbuf;
pub(crate) mod task;
pub(crate) mod value;
pub(crate) mod vm;

pub use error::{FrameInfo, RuntimeError, VmResult};
pub use frame::VM_STACK_BYTES;
pub use globals::GlobalStore;
pub use heap::{Heap, HeapObj};
pub use loader::{CompositeLoader, ModuleError, ModuleLoader};
pub use profile::{CallEntry, HotspotCounters, ProfileCounters, VmProfile};
pub use settings::ExecSettings;
pub use value::VmValue;
pub use vm::{prefill_native_modules, Vm};
