[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
varn-core     = { path = "../crates/varn-core" }
varn-lexer    = { path = "../crates/varn-lexer" }
varn-parser   = { path = "../crates/varn-parser" }
varn-modules  = { path = "../crates/varn-modules" }
varn-builtins = { path = "../crates/varn-builtins", features = ["runtime"] }
varn-checker  = { path = "../crates/varn-checker" }
varn-pipeline = { path = "../crates/varn-pipeline" }
serde         = { workspace = true }
serde_json    = { workspace = true }
postcard      = { version = "1", features = ["alloc"] }
