use varn_core::OpCode;

pub(super) fn implied(op: OpCode) -> Option<&'static str> {
    Some(match op {
        OpCode::LoadNull => "null",
        OpCode::LoadTrue => "true",
        OpCode::LoadFalse => "false",
        OpCode::LoadIntZero => "0",
        OpCode::LoadIntOne => "1",
        OpCode::LoadIntMinusOne => "-1",
        OpCode::LoadConst
        | OpCode::LoadInt
        | OpCode::Move
        | OpCode::LoadGlobal
        | OpCode::StoreGlobal
        | OpCode::DefineGlobal
        | OpCode::DefineGlobalIdx
        | OpCode::LoadGlobalIdx
        | OpCode::StoreGlobalIdx
        | OpCode::LoadUpvalue
        | OpCode::StoreUpvalue
        | OpCode::CloseUpvalue
        | OpCode::Add
        | OpCode::Sub
        | OpCode::Mul
        | OpCode::Div
        | OpCode::Mod
        | OpCode::Pow
        | OpCode::Negate
        | OpCode::Not
        | OpCode::ToString
        | OpCode::Eq
        | OpCode::Neq
        | OpCode::Lt
        | OpCode::Lte
        | OpCode::Gt
        | OpCode::Gte
        | OpCode::BitAnd
        | OpCode::BitOr
        | OpCode::BitXor
        | OpCode::Shl
        | OpCode::Shr
        | OpCode::Ushr
        | OpCode::Jump
        | OpCode::JumpIfFalse
        | OpCode::JumpIfTrue
        | OpCode::Loop
        | OpCode::Call
        | OpCode::CallMethod
        | OpCode::InvokeVirtual
        | OpCode::CallSpread
        | OpCode::Return
        | OpCode::BuildArray
        | OpCode::BuildTuple
        | OpCode::BuildObject
        | OpCode::BuildObjectWithShape
        | OpCode::BuildRecord
        | OpCode::GetIndex
        | OpCode::SetIndex
        | OpCode::ObjectRest
        | OpCode::ObjectKeys
        | OpCode::ObjectMerge
        | OpCode::GetProperty
        | OpCode::GetPropertyMaybe
        | OpCode::SetProperty
        | OpCode::GetFixedField
        | OpCode::SetFixedField
        | OpCode::GetSuper
        | OpCode::GetSymbol
        | OpCode::MakeClosure
        | OpCode::MakeClass
        | OpCode::Inherit
        | OpCode::Method
        | OpCode::DefineStatic
        | OpCode::DefineGetter
        | OpCode::DefineSetter
        | OpCode::DefineStaticGetter
        | OpCode::DefineStaticSetter
        | OpCode::DeclareLayout
        | OpCode::AllocInstance
        | OpCode::BindMethod
        | OpCode::Typeof
        | OpCode::Instanceof
        | OpCode::In
        | OpCode::IsNull
        | OpCode::IsArray
        | OpCode::AssertNotNull
        | OpCode::StrConcat
        | OpCode::StrLength
        | OpCode::StrSlice
        | OpCode::ArrayLength
        | OpCode::ArrayPush
        | OpCode::ArrayPop
        | OpCode::ArrayExtend
        | OpCode::WrapSpread
        | OpCode::MakeEnumVariant
        | OpCode::GetEnumTag
        | OpCode::Await
        | OpCode::Spawn
        | OpCode::Yield
        | OpCode::Try
        | OpCode::Throw
        | OpCode::PopTry
        | OpCode::LoadModule
        | OpCode::LoadModuleSlot
        | OpCode::StoreModuleSlot
        | OpCode::InvokeRuntimeStatic
        | OpCode::AddImm
        | OpCode::SubImm
        | OpCode::BuildStr
        | OpCode::AddInt
        | OpCode::SubInt
        | OpCode::MulInt
        | OpCode::DivInt
        | OpCode::LtInt
        | OpCode::GtInt
        | OpCode::LteInt
        | OpCode::GteInt
        | OpCode::EqInt
        | OpCode::NeqInt
        | OpCode::AddFloat
        | OpCode::SubFloat
        | OpCode::MulFloat
        | OpCode::DivFloat
        | OpCode::ModFloat
        | OpCode::PowFloat
        | OpCode::LtFloat
        | OpCode::GtFloat
        | OpCode::LteFloat
        | OpCode::GteFloat
        | OpCode::EqFloat
        | OpCode::NeqFloat
        | OpCode::ModInt
        | OpCode::PowInt
        | OpCode::Intrinsic
        | OpCode::LoadStaticFn
        | OpCode::CallSelf
        | OpCode::Nop
        | OpCode::ArrayGetIndex
        | OpCode::ArraySetIndex
        | OpCode::CallNativeOp
        | OpCode::IntrinsicDirect
        | OpCode::LoadNativeGlobalIdx
        | OpCode::BuildMap
        | OpCode::MapGetIndex
        | OpCode::MapSetIndex
        | OpCode::Convert
        | OpCode::BytesLength => return None,
    })
}
