[package]
name = "varn-resolver"
version.workspace = true
edition.workspace = true

[dependencies]
varn-sem     = { path = "../varn-sem" }
varn-binder  = { path = "../varn-binder" }
varn-core    = { path = "../varn-core" }
varn-modules = { path = "../varn-modules" }
varn-lexer   = { path = "../varn-lexer" }
varn-parser  = { path = "../varn-parser" }
rustc-hash   = { workspace = true }
parking_lot  = { workspace = true }

[lints]
workspace = true
