pub struct KwEntry {
    pub label: &'static str,
    pub detail: Option<&'static str>,
    pub doc: Option<&'static str>,
    pub snippet: Option<&'static str>,
}

pub const fn kw(label: &'static str) -> KwEntry {
    KwEntry {
        label,
        detail: None,
        doc: None,
        snippet: None,
    }
}

pub const fn kw_snip(label: &'static str, detail: &'static str, snippet: &'static str) -> KwEntry {
    KwEntry {
        label,
        detail: Some(detail),
        doc: None,
        snippet: Some(snippet),
    }
}

pub static KEYWORDS: &[KwEntry] = &[
    kw("let"),
    kw("const"),
    kw("var"),
    kw_snip(
        "function",
        "fn declaration",
        "function ${1:name}(${2:params}) {\n\t$0\n}",
    ),
    kw_snip("class", "class declaration", "class ${1:Name} {\n\t$0\n}"),
    kw_snip(
        "struct",
        "struct declaration",
        "struct ${1:Name} {\n\t$0\n}",
    ),
    kw_snip("interface", "interface", "interface ${1:Name} {\n\t$0\n}"),
    kw("type"),
    kw("enum"),
    kw("namespace"),
    kw("module"),
    kw("extension"),
    kw("on"),
    kw_snip("if", "conditional", "if (${1:condition}) {\n\t$0\n}"),
    kw("else"),
    kw_snip(
        "switch",
        "switch",
        "switch (${1:expr}) {\n\tcase ${2:value}:\n\t\t$0\n}",
    ),
    kw("case"),
    kw("default"),
    kw_snip("while", "while loop", "while (${1:condition}) {\n\t$0\n}"),
    kw_snip(
        "for",
        "for loop",
        "for (${1:init}; ${2:cond}; ${3:update}) {\n\t$0\n}",
    ),
    kw("do"),
    kw("break"),
    kw("continue"),
    kw("return"),
    kw("throw"),
    kw_snip(
        "try",
        "try/catch",
        "try {\n\t$1\n} catch (${2:e}) {\n\t$0\n}",
    ),
    kw("catch"),
    kw("finally"),
    kw("using"),
    kw("import"),
    kw("export"),
    kw("from"),
    kw("as"),
    kw("async"),
    kw("await"),
    kw("yield"),
    kw("new"),
    kw("this"),
    kw("super"),
    kw("delete"),
    kw("typeof"),
    kw("instanceof"),
    kw("in"),
    kw("of"),
    kw("void"),
    kw("is"),
    kw("true"),
    kw("false"),
    kw("null"),
    kw("public"),
    kw("private"),
    kw("protected"),
    kw("static"),
    kw("abstract"),
    kw("override"),
    kw("readonly"),
    kw("declare"),
    kw("native"),
    kw("extends"),
    kw("implements"),
    kw("get"),
    kw("set"),
    kw("constructor"),
    kw("destructor"),
    kw_snip(
        "match",
        "pattern match",
        "match (${1:expr}) {\n\t${2:pattern} => $0\n}",
    ),
];
