#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MemberKey {
    Tag,
    Value0,
    RawValue,
    Length,
    Size,
    Name,
    VariantName,
    Variant,
    Callable,
    ToString,
    ValueOf,
    IterNext,
    IterDone,
    IterValue,
    Push,
    Pop,
    Shift,
    Unshift,
    Slice,
    Join,
    IndexOf,
    Includes,
    Split,
    Class,
    Type,
    Fields,
    Methods,
    Keys,
    Values,
    Entries,
    HasOwn,
    Repeat,
    PadStart,
    PadEnd,
    Start,
    End,
    StartsWith,
    EndsWith,
    CharCodeAt,
    CodePointAt,
    Substring,
    Substr,
    At,
    LastIndexOf,
    CharCode,
}

impl MemberKey {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Tag => "__tag",
            Self::Value0 => "value0",
            Self::RawValue => "rawValue",
            Self::Length => "length",
            Self::Size => "size",
            Self::Name => "name",
            Self::VariantName => "__variant_name__",
            Self::Variant => "__variant__",
            Self::Callable => "()",
            Self::ToString => "toString",
            Self::ValueOf => "valueOf",
            Self::IterNext => "next",
            Self::IterDone => "done",
            Self::IterValue => "value",
            Self::Push => "push",
            Self::Pop => "pop",
            Self::Shift => "shift",
            Self::Unshift => "unshift",
            Self::Slice => "slice",
            Self::Join => "join",
            Self::IndexOf => "indexOf",
            Self::Includes => "includes",
            Self::Split => "split",
            Self::Class => "class",
            Self::Type => "type",
            Self::Fields => "fields",
            Self::Methods => "methods",
            Self::Keys => "keys",
            Self::Values => "values",
            Self::Entries => "entries",
            Self::HasOwn => "hasOwn",
            Self::Repeat => "repeat",
            Self::PadStart => "padStart",
            Self::PadEnd => "padEnd",
            Self::Start => "start",
            Self::End => "end",
            Self::StartsWith => "startsWith",
            Self::EndsWith => "endsWith",
            Self::CharCodeAt => "charCodeAt",
            Self::CodePointAt => "codePointAt",
            Self::Substring => "substring",
            Self::Substr => "substr",
            Self::At => "at",
            Self::LastIndexOf => "lastIndexOf",
            Self::CharCode => "charCode",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "__tag" => Some(Self::Tag),
            "value0" => Some(Self::Value0),
            "rawValue" => Some(Self::RawValue),
            "length" => Some(Self::Length),
            "size" => Some(Self::Size),
            "name" => Some(Self::Name),
            "__variant_name__" => Some(Self::VariantName),
            "__variant__" => Some(Self::Variant),
            "()" => Some(Self::Callable),
            "toString" => Some(Self::ToString),
            "valueOf" => Some(Self::ValueOf),
            "next" => Some(Self::IterNext),
            "done" => Some(Self::IterDone),
            "value" => Some(Self::IterValue),
            "push" => Some(Self::Push),
            "pop" => Some(Self::Pop),
            "shift" => Some(Self::Shift),
            "unshift" => Some(Self::Unshift),
            "slice" => Some(Self::Slice),
            "join" => Some(Self::Join),
            "indexOf" => Some(Self::IndexOf),
            "includes" => Some(Self::Includes),
            "split" => Some(Self::Split),
            "class" => Some(Self::Class),
            "type" => Some(Self::Type),
            "fields" => Some(Self::Fields),
            "methods" => Some(Self::Methods),
            "keys" => Some(Self::Keys),
            "values" => Some(Self::Values),
            "entries" => Some(Self::Entries),
            "hasOwn" => Some(Self::HasOwn),
            "repeat" => Some(Self::Repeat),
            "padStart" => Some(Self::PadStart),
            "padEnd" => Some(Self::PadEnd),
            "start" => Some(Self::Start),
            "end" => Some(Self::End),
            "startsWith" => Some(Self::StartsWith),
            "endsWith" => Some(Self::EndsWith),
            "charCodeAt" => Some(Self::CharCodeAt),
            "codePointAt" => Some(Self::CodePointAt),
            "substring" => Some(Self::Substring),
            "substr" => Some(Self::Substr),
            "at" => Some(Self::At),
            "lastIndexOf" => Some(Self::LastIndexOf),
            "charCode" => Some(Self::CharCode),
            _ => None,
        }
    }
}
