[package]
name = "varn-checker"
version.workspace = true
edition.workspace = true

[dependencies]
varn-core     = { path = "../varn-core" }
rustc-hash    = { workspace = true }

varn-sem      = { path = "../varn-sem" }
varn-binder   = { path = "../varn-binder" }

[dev-dependencies]
varn-sem = { path = "../varn-sem" }

[lints]
workspace = true
