[package]
name = "varn-debug"
version.workspace = true
edition.workspace = true

[features]
clif = ["varn-jit/clif"]

[dependencies]
console       = { workspace = true }
varn-core     = { path = "../varn-core" }
varn-emit     = { path = "../varn-emit" }
varn-tir      = { path = "../varn-tir" }
varn-types    = { path = "../varn-types" }
varn-sem      = { path = "../varn-sem" }
varn-compiler = { path = "../varn-compiler" }
varn-jit      = { path = "../varn-jit" }
rustc-hash    = { workspace = true }
iced-x86      = "1"

[lints]
workspace = true
