pub mod ast;
pub mod binds;
pub mod bytecode;
pub mod cap_trace;
pub mod clif;
pub mod colors;
pub mod consts;
pub mod error;
pub mod expr;
pub mod flags;
pub mod hir;
pub mod loop_diagnostics;
pub mod modules;
pub mod roots;
pub mod scope;
pub mod ssa;
pub mod summary;
pub mod symbols;
pub mod tiers;
pub mod tokens;
pub mod types;

pub use cap_trace::debug_cap_trace;
pub use flags::{print_phases, DebugFlags};
