[package]
name = "varn-jit"
version.workspace = true
edition.workspace = true

[dependencies]
varn-core = { path = "../varn-core" }
varn-types = { path = "../varn-types" }
cranelift-codegen = { version = "0.125.4", default-features = false, features = ["x86", "arm64", "std"] }
cranelift-frontend = "0.125.4"
cranelift-native = "0.125.4"

[lints]
workspace = true
