[package]
name = "varn-jit"
version.workspace = true
edition.workspace = true

[dependencies]
varn-core = { path = "../varn-core" }
varn-jit-abi = { path = "../varn-jit-abi" }
varn-types = { path = "../varn-types" }
cranelift-codegen = { version = "0.136.2", default-features = false, features = ["x86", "arm64", "std"], optional = true }
cranelift-frontend = { version = "0.136.2", optional = true }
cranelift-native = { version = "0.136.2", optional = true }
cranelift-module = { version = "0.136.2", optional = true }
cranelift-object = { version = "0.136.2", optional = true }
rustc-hash = { workspace = true, optional = true }

[features]
default = []
clif = [
    "dep:cranelift-codegen",
    "dep:cranelift-frontend",
    "dep:cranelift-module",
    "dep:cranelift-native",
    "dep:cranelift-object",
    "dep:rustc-hash",
]

[lints]
workspace = true
