[package]
name = "varn-cli"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "vn"
path = "src/main.rs"

[[bin]]
name = "debug_binder"
path = "src/debug_binder.rs"

[dependencies]
varn-utilities = { path = "../varn-utilities" }
varn-pipeline = { path = "../varn-pipeline", features = ["lsp-debug"] }
varn-core     = { path = "../varn-core" }
varn-lexer    = { path = "../varn-lexer" }
varn-parser   = { path = "../varn-parser", features = ["profiling"] }
varn-checker  = { path = "../varn-checker" }
varn-opt      = { path = "../varn-opt" }
varn-backend  = { path = "../varn-backend" }
varn-vm       = { path = "../varn-vm", features = ["profiling"] }
varn-builtins = { path = "../varn-builtins", features = ["runtime"] }
varn-types    = { path = "../varn-types" }
varn-debug    = { path = "../varn-debug" }
varn-lsp      = { path = "../varn-lsp" }
varn-pm       = { path = "../varn-pm" }
varn-modules  = { path = "../varn-modules" }
tower-lsp        = { workspace = true }
postcard         = { version = "1", features = ["alloc"] }
clap             = { version = "4", features = ["derive"] }
clap_complete    = "4"
rustc-hash       = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
