use crate::token_kind::{
    ABSTRACT, AS, ASYNC, AWAIT, BREAK, CASE, CATCH, CLASS, CONST, CONSTRUCTOR, CONTINUE, DECLARE,
    DEFAULT, DELETE, DESTRUCTOR, DO, ELSE, ENUM, EXPORT, EXTENDS, EXTENSION, FALSE, FINALLY, FOR,
    FROM, FUNCTION, GET, IDENTIFIER, IF, IMPLEMENTS, IMPORT, IN, INSTANCEOF, INTERFACE, IS, LET,
    MATCH, MODULE, NAMESPACE, NATIVE, NEW, NULL, OF, ON, OVERRIDE, PLACEHOLDER, PRIVATE, PROTECTED,
    PUBLIC, READONLY, RETURN, SET, STATIC, STRUCT, SUPER, SWITCH, THIS, THROW, TRUE, TRY, TYPE,
    TYPEOF, USING, VAR, VOID, WHILE, WITH, YIELD,
};

pub(crate) fn keyword_kind(raw: &[u8]) -> u32 {
    match raw {
        b"let" => LET,
        b"const" => CONST,
        b"var" => VAR,
        b"function" => FUNCTION,
        b"class" => CLASS,
        b"struct" => STRUCT,
        b"interface" => INTERFACE,
        b"type" => TYPE,
        b"enum" => ENUM,
        b"namespace" => NAMESPACE,
        b"module" => MODULE,
        b"extension" => EXTENSION,
        b"on" => ON,
        b"if" => IF,
        b"else" => ELSE,
        b"switch" => SWITCH,
        b"case" => CASE,
        b"default" => DEFAULT,
        b"while" => WHILE,
        b"for" => FOR,
        b"do" => DO,
        b"break" => BREAK,
        b"continue" => CONTINUE,
        b"return" => RETURN,
        b"throw" => THROW,
        b"try" => TRY,
        b"catch" => CATCH,
        b"finally" => FINALLY,
        b"using" => USING,
        b"with" => WITH,
        b"import" => IMPORT,
        b"export" => EXPORT,
        b"from" => FROM,
        b"as" => AS,
        b"async" => ASYNC,
        b"await" => AWAIT,
        b"yield" => YIELD,
        b"new" => NEW,
        b"this" => THIS,
        b"super" => SUPER,
        b"delete" => DELETE,
        b"typeof" => TYPEOF,
        b"instanceof" => INSTANCEOF,
        b"in" => IN,
        b"of" => OF,
        b"void" => VOID,
        b"is" => IS,
        b"true" => TRUE,
        b"false" => FALSE,
        b"null" => NULL,
        b"public" => PUBLIC,
        b"private" => PRIVATE,
        b"protected" => PROTECTED,
        b"static" => STATIC,
        b"abstract" => ABSTRACT,
        b"override" => OVERRIDE,
        b"readonly" => READONLY,
        b"declare" => DECLARE,
        b"native" => NATIVE,
        b"extends" => EXTENDS,
        b"implements" => IMPLEMENTS,
        b"get" => GET,
        b"set" => SET,
        b"constructor" => CONSTRUCTOR,
        b"destructor" => DESTRUCTOR,
        b"match" => MATCH,
        b"_" => PLACEHOLDER,
        _ => IDENTIFIER,
    }
}
