[package]
name = "varn-pm"
version.workspace = true
edition.workspace = true

[dependencies]
varn-term      = { path = "../varn-term" }
varn-modules = { path = "../varn-modules" }
serde      = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }
semver     = { workspace = true }
ureq = { version = "2", features = ["json"] }
sha2 = { workspace = true }
hex  = { workspace = true }
tar = "0.4"
flate2 = "1"

[lints]
workspace = true
