[package]
name = "varn-pm"
version = "0.1.0"
edition = "2021"

[dependencies]
varn-modules = { path = "../varn-modules" }
serde      = { workspace = true }
serde_json = { workspace = true }
semver     = "1"
ureq = { version = "2", features = ["json"] }
sha2 = "0.10"
hex = "0.4"
tar = "0.4"
flate2 = "1"
