[package]
name = "varn-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde      = { workspace = true, features = ["rc"] }
num-bigint = { workspace = true }
num-traits = { workspace = true }
rustc-hash = { workspace = true }

[features]
default = []

[lints]
workspace = true
